name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install Trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: 'latest'

      - name: Compress Assets
        run: |
          # -9 = Best compression
          # -k = Keep original file (optional, but good for debugging)
          # -f = Force overwrite if exists
          gzip -9 -f assets/rszmhwilds_packed.json
          gzip -9 -f assets/enumsmhwilds.json
          ls -lh assets/

      - name: Build with Trunk
        run: trunk build gui/index.html --release --public-url /mhtame/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
