name: Deploy to GitHub Pages

on:
  push:
    branches: [ "web" ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install Trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: 'latest'

      - name: Compress Assets
        run: |
          rm assets/mhwilds/rszmhwilds.json # need to do this bc its >100mb
          gzip -9 -f assets/mhwilds/rszmhwilds_packed.json
          gzip -9 -f assets/mhwilds/enumsmhwilds.json
          gzip -9 -f assets/mhwilds/combined_msgs.json
          ls -lh assets/

      - name: Build with Trunk
        run: trunk build gui/index.html --release --public-url /ree-save-editor/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
